version: '3.8'
services:
  mongodb:
    image: mongo:4.4.18
    ports:
      - "17017:27017"
    container_name: mongodb_container

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis_container

  app:
    build: .
    ports:
      - "17017:17017"
      - "6379:6379"
    depends_on:
      - mongodb
      - redis
